replicaCount: 1

image:
  repository: esbalo/tuv
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containerPort: 3000

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
  - host: tuv.landbot.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []

resources: {}
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 50%

nodeSelector: {}

tolerations: []

antiaffinity:
  enabled: true

prestop:
  enabled: true

configmap:
  REDIS_HOST: <Host of the redis instance>
  REDIS_PORT: <Port of the redis instance>
  REDIS_USERNAME: <Redis instance username>
  
secret:
  REDIS_PASSWORD: <Redis instance password>